"""Captions stage: turn voice timing into a styled ASS caption track.

Reads voice/index.json (produced by the voice stage), assigns each line a
display window, and writes captions.ass. ASS bakes style, font, color, and
position into the file itself, so the render stage can hand it to FFmpeg's
subtitle filter unchanged.

Caption styles are named presets defined in this module. Specs pick a style
by name in visual.caption_style.

Limitation: line-level only. One voice chunk = one caption block. Word-level
captioning requires a forced-alignment pass (Whisper on the rendered audio)
and is deliberately deferred.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from motive_engine.schemas import ContentSpec
from motive_engine.stages.voice import VoiceTrack


@dataclass(frozen=True)
class CaptionStyle:
    """One named caption style preset (ASS V4+)."""

    name: str
    font: str
    font_size: int
    primary_color: str   # ASS color: &HAABBGGRR
    outline_color: str
    outline_size: int
    shadow_depth: int
    bold: bool
    alignment: int       # ASS alignment 1-9 (8 = top-center)
    margin_v: int        # vertical margin (px), from the side `alignment` anchors to


# Hand-picked styles. Fonts chosen for Windows availability + aesthetic fit.
# Captions placed upper-third per the project's image-prompt convention.
CAPTION_STYLES: dict[str, CaptionStyle] = {
    "serif_quiet": CaptionStyle(
        name="serif_quiet",
        font="Georgia",
        font_size=104,
        primary_color="&H00FFFFFF",   # white
        outline_color="&H00000000",   # black
        outline_size=3,
        shadow_depth=2,
        bold=False,
        alignment=8,                  # top-center
        margin_v=280,                 # ~upper-third on 1920px tall frame
    ),
    "sans_quiet": CaptionStyle(
        name="sans_quiet",
        font="Segoe UI",
        font_size=100,
        primary_color="&H00FFFFFF",
        outline_color="&H00000000",
        outline_size=3,
        shadow_depth=2,
        bold=False,
        alignment=8,
        margin_v=280,
    ),
}


class CaptionLine(BaseModel):
    model_config = ConfigDict(extra="forbid")

    index: int = Field(ge=1)
    start_seconds: float = Field(ge=0)
    end_seconds: float = Field(gt=0)
    text: str = Field(min_length=1)


class CaptionTrack(BaseModel):
    model_config = ConfigDict(extra="forbid")

    spec_id: str
    style: str
    resolution: str
    lines: list[CaptionLine]


# ---- public API ------------------------------------------------------------


def get_caption_style(name: str) -> CaptionStyle:
    """Look up a caption style by name."""
    if name not in CAPTION_STYLES:
        available = ", ".join(sorted(CAPTION_STYLES))
        raise KeyError(f"Unknown caption style '{name}' (available: {available})")
    return CAPTION_STYLES[name]


def load_voice_track(voice_dir: Path) -> VoiceTrack:
    """Load voice/index.json into a VoiceTrack."""
    index_path = voice_dir / "index.json"
    if not index_path.is_file():
        raise FileNotFoundError(
            f"No voice/index.json at {index_path}. Run `motive make-voice` first."
        )
    data = json.loads(index_path.read_text(encoding="utf-8"))
    return VoiceTrack.model_validate(data)


def build_caption_track(spec: ContentSpec, voice_track: VoiceTrack) -> CaptionTrack:
    """Compose a CaptionTrack from a VoiceTrack by accumulating durations."""
    lines: list[CaptionLine] = []
    cursor = 0.0
    counter = 0
    for vline in voice_track.lines:
        text = vline.graphemes.strip()
        # Voice lines with no readable text still advance the cursor.
        if not text:
            cursor += vline.duration_seconds
            continue
        counter += 1
        end = cursor + vline.duration_seconds
        lines.append(
            CaptionLine(
                index=counter,
                start_seconds=cursor,
                end_seconds=end,
                text=text,
            )
        )
        cursor = end
    return CaptionTrack(
        spec_id=spec.id,
        style=spec.visual.caption_style,
        resolution=spec.render.resolution,
        lines=lines,
    )


def render_ass(track: CaptionTrack, style: CaptionStyle) -> str:
    """Serialize a CaptionTrack to ASS V4+ format."""
    width, height = (int(x) for x in track.resolution.split("x"))
    parts: list[str] = []

    parts.append("[Script Info]")
    parts.append(f"; Generated by motive-engine for spec {track.spec_id}")
    parts.append("ScriptType: v4.00+")
    parts.append(f"PlayResX: {width}")
    parts.append(f"PlayResY: {height}")
    parts.append("ScaledBorderAndShadow: yes")
    parts.append("")

    parts.append("[V4+ Styles]")
    parts.append(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding"
    )
    parts.append(
        f"Style: {style.name},{style.font},{style.font_size},"
        f"{style.primary_color},&H000000FF,{style.outline_color},&H00000000,"
        f"{-1 if style.bold else 0},0,0,0,100,100,0,0,1,"
        f"{style.outline_size},{style.shadow_depth},"
        f"{style.alignment},20,20,{style.margin_v},1"
    )
    parts.append("")

    parts.append("[Events]")
    parts.append(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    )
    for line in track.lines:
        start = _format_ass_time(line.start_seconds)
        end = _format_ass_time(line.end_seconds)
        text = line.text.replace("\n", "\\N")
        parts.append(f"Dialogue: 0,{start},{end},{style.name},,0,0,0,,{text}")

    return "\n".join(parts) + "\n"


def write_captions(spec: ContentSpec, output_root: Path) -> tuple[Path, CaptionTrack]:
    """End-to-end: load voice track, build captions, write captions.ass."""
    style = get_caption_style(spec.visual.caption_style)
    voice_track = load_voice_track(output_root / spec.id / "voice")
    track = build_caption_track(spec, voice_track)
    ass = render_ass(track, style)
    output_path = output_root / spec.id / "captions.ass"
    output_path.write_text(ass, encoding="utf-8")
    return output_path, track


# ---- internals -------------------------------------------------------------


def _format_ass_time(seconds: float) -> str:
    """Format seconds as H:MM:SS.cc (ASS V4+ time format)."""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = seconds - hours * 3600 - minutes * 60
    return f"{hours}:{minutes:02d}:{secs:05.2f}"
